name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies
        run: |
          uv pip install --system .

      - name: Run tests
        run: |
          uv run pytest tests/

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies
        run: |
          uv pip install --system -e ".[dev]"

      - name: Check code with ruff
        run: |
          uv run ruff check .

      - name: Show formatting diff with ruff
        run: |
          uv run ruff format --diff moonwell/bad_debt.py moonwell/proposals.py

      - name: Fix formatting with ruff
        run: |
          uv run ruff format moonwell/bad_debt.py moonwell/proposals.py

      - name: Verify formatting is fixed
        run: |
          uv run ruff format --check .

      - name: Show git diff after formatting
        run: |
          git diff
