name: Monitoring Scripts

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: # manual for testing

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Aave script
        run: |
          cd aave && python main.py && cd ..
        env:
          TELEGRAM_BOT_TOKEN_AAVE: ${{ secrets.TELEGRAM_BOT_TOKEN_AAVE }}
          TELEGRAM_CHAT_ID_AAVE: ${{ secrets.TELEGRAM_CHAT_ID_AAVE }}
          PROVIDER_URL: ${{ secrets.PROVIDER_URL }}
          PROVIDER_URL_MAINNET: ${{ secrets.PROVIDER_URL_MAINNET }}
          PROVIDER_URL_ARBITRUM: ${{ secrets.PROVIDER_URL_ARBITRUM }}
          PROVIDER_URL_OPTIMISM: ${{ secrets.PROVIDER_URL_OPTIMISM }}
      - name: Run Lido Polygon script
        run: cd lido-polygon && python main.py && cd ..
        env:
          TELEGRAM_BOT_TOKEN_STMATIC: ${{ secrets.TELEGRAM_BOT_TOKEN_STMATIC }}
          TELEGRAM_CHAT_ID_STMATIC: ${{ secrets.TELEGRAM_CHAT_ID_STMATIC }}
          PROVIDER_URL: ${{ secrets.PROVIDER_URL }}
          PROVIDER_URL_MAINNET: ${{ secrets.PROVIDER_URL_MAINNET }}
      - name: Run Stargate script
        run: cd stargate && python main.py && cd ..
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PROVIDER_URL: ${{ secrets.PROVIDER_URL }}
          PROVIDER_URL_ARBITRUM: ${{ secrets.PROVIDER_URL_ARBITRUM }}
