name: Hourly Monitoring Scripts

on:
  schedule:
    - cron: "26 * * * *"
  workflow_dispatch:

# Add concurrency control
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROVIDER_URL_POLYGON: ${{ secrets.PROVIDER_URL }}
  PROVIDER_URL_OPTIMISM: ${{ secrets.PROVIDER_URL_OPTIMISM }}
  PROVIDER_URL_MAINNET: ${{ secrets.PROVIDER_URL_MAINNET }}
  PROVIDER_URL_ARBITRUM: ${{ secrets.PROVIDER_URL_ARBITRUM }}
  PROVIDER_URL_BASE: ${{ secrets.PROVIDER_URL_BASE }}
  TELEGRAM_BOT_TOKEN_AAVE: ${{ secrets.TELEGRAM_BOT_TOKEN_AAVE }}
  TELEGRAM_CHAT_ID_AAVE: ${{ secrets.TELEGRAM_CHAT_ID_AAVE }}
  TELEGRAM_BOT_TOKEN_COMP: ${{ secrets.TELEGRAM_BOT_TOKEN_COMP }}
  TELEGRAM_CHAT_ID_COMP: ${{ secrets.TELEGRAM_CHAT_ID_COMP }}
  TELEGRAM_BOT_TOKEN_LIDO: ${{ secrets.TELEGRAM_BOT_TOKEN_LIDO }}
  TELEGRAM_CHAT_ID_LIDO: ${{ secrets.TELEGRAM_CHAT_ID_LIDO }}
  TELEGRAM_BOT_TOKEN_SILO: ${{ secrets.TELEGRAM_BOT_TOKEN_SILO }}
  TELEGRAM_CHAT_ID_SILO: ${{ secrets.TELEGRAM_CHAT_ID_SILO }}
  TELEGRAM_BOT_TOKEN_STARGATE: ${{ secrets.TELEGRAM_BOT_TOKEN_STARGATE }}
  TELEGRAM_CHAT_ID_STARGATE: ${{ secrets.TELEGRAM_CHAT_ID_STARGATE }}
  TELEGRAM_BOT_TOKEN_SPARK: ${{ secrets.TELEGRAM_BOT_TOKEN_SPARK }}
  TELEGRAM_CHAT_ID_SPARK: ${{ secrets.TELEGRAM_CHAT_ID_SPARK }}
  TELEGRAM_BOT_TOKEN_PENDLE: ${{ secrets.TELEGRAM_BOT_TOKEN_PENDLE }}
  TELEGRAM_CHAT_ID_PENDLE: ${{ secrets.TELEGRAM_CHAT_ID_PENDLE }}
  TELEGRAM_BOT_TOKEN_PEGS: ${{ secrets.TELEGRAM_BOT_TOKEN_PEGS }}
  TELEGRAM_CHAT_ID_PEGS: ${{ secrets.TELEGRAM_CHAT_ID_PEGS }}
  TELEGRAM_CHAT_ID_MORPHO: ${{ secrets.TELEGRAM_CHAT_ID_MORPHO }}
  TELEGRAM_CHAT_ID_USD0: ${{ secrets.TELEGRAM_CHAT_ID_USD0 }}
  TELEGRAM_CHAT_ID_MOONWELL: ${{ secrets.TELEGRAM_CHAT_ID_MOONWELL }}
  TELEGRAM_BOT_TOKEN_DEFAULT: ${{ secrets.TELEGRAM_BOT_TOKEN_DEFAULT }}
  GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }}
  TALLY_API_KEY: ${{ secrets.TALLY_API_KEY }}
  ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
  POLYGONSCAN_TOKEN: ${{ secrets.POLYGONSCAN_TOKEN }}
  OPTIMISMSCAN_TOKEN: ${{ secrets.OPTIMISMSCAN_TOKEN }}
  ARBISCAN_TOKEN: ${{ secrets.ARBISCAN_TOKEN }}

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Install dependencies
        run: |
          uv pip install .

      # restore file from cache
      - name: Get cache file
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: cache-id.txt
          key: cache-id-v4-${{ hashFiles('cache-id.txt') }}
          restore-keys: |
            cache-id-v4-

      # Get initial hash
      - name: Get initial hash
        id: initial-hash
        run: echo "hash=${{ hashFiles('cache-id.txt') }}" >> $GITHUB_OUTPUT

      - name: Run Aave script
        run: python aave.main
      - name: Run Aave Proposals script
        run: python aave.proposals
      - name: Run Spark script
        run: python spark.main
      - name: Run Compound script
        run: python compound.main
      - name: Run Compound Proposals script
        run: python compound.proposals
      - name: Run Lido Matic script
        run: python lido.stmatic.main
      - name: Run Lido Ethereum script
        run: python lido.steth.main
      # - name: Run Stargate script
      #   run: python stargate.main
      - name: Run Silo Utilization script
        run: python silo.ur_sniff
      # - name: Run Silo Bad Debt script
      #   run: python silo.main
      - name: Run Pendle price script
        run: python pendle.main
      - name: Run LRT Peg Checker Balancer
        run: python lrt-pegs.balancer.main
      - name: Run Morpho Governance Monitoring script
        run: python morpho.governance
      - name: Run Morpho Bad Debt script
        run: python morpho.markets
      - name: Run Moonwell Bad Debt script
        run: python moonwell.bad_debt
      - name: Run Moonwell Proposals script
        run: python moonwell.proposals
      # - name: Run USD0 Peg Price Checker
      #   run: python usd0.price

      # Check final hash
      - name: Check final hash
        id: final-hash
        run: echo "hash=${{ hashFiles('cache-id.txt') }}" >> $GITHUB_OUTPUT

      - name: Cache cache-id.txt
        if: always() && steps.initial-hash.outputs.hash != steps.final-hash.outputs.hash
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: cache-id.txt
          key: cache-id-v4-${{ hashFiles('cache-id.txt') }}
